[package]
name = "json_parser"
version = "0.1.0"
edition = "2024"

[[bin]]
name="check"
path="./bin/check.rs"

[[bin]]
name="generate_corpus"
path="./bin/generate_corpus.rs"


[dependencies]
arbitrary = "1.4.2"

[dev-dependencies]
